services:
  sms-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smsdb
      QUARKUS_DATASOURCE_USERNAME: quarkus
      QUARKUS_DATASOURCE_PASSWORD: quarkus

  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: smsdb
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
    ports:
      - "5432:5432"
